#!/usr/bin/env bash	
#install and configure ufw and set up
#configure ufw to block all incoming traffic except for the following TCP ports 22(SSH) 443(HTTPS SSL) and 80(HTTP)

sudo apt install ufw
sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
